# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name_plural': 'Utenti di sistema'},
        ),
    ]
